services:
  voidauth:
    build: .
    restart: unless-stopped
    volumes:
      - ./voidauth-data/config:/app/config
      - ./voidauth-data/db:/app/db
    ports:
      - "3002:3000"
    environment:
      APP_URL: https://192.168.0.6:3001
      DB_ADAPTER: sqlite
      STORAGE_KEY: 5a849c3878c11c7ee79a8a4a6f21879a1f77118e9a718fd2845c6ea2b48bdf35
